### ISSUE TITLE
num of smaples coming 0 after pickling

### ISSUE THREAD

**Issue by Jatinrajpal** [n0obcoder/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch#4]
Traceback (most recent call last):
  File "E:\btp final\NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch\main.py", line 89, in <module>
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size = batch_size, shuffle = True)
  File "C:\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "C:\Python38\lib\site-packages\torch\utils\data\sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by ishikakhurana011** [comment]
how was this issue resolved? I am getting the same error

**Comment by Jatinrajpal** [comment]
I will have a look at it this weekend, as i don't remember properly how it was fixed.

**Comment by ishikakhurana011** [comment]
okay, thank you @Jatinrajpal
